
package com.mindbodyonline.clients.api._0_5_1.sale_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sale_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SaleX0020ServiceSoap {


    /**
     * Gets a list of card types that the site accepts.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetAcceptedCardTypeResult
     */
    @WebMethod(operationName = "GetAcceptedCardType", action = "http://clients.mindbodyonline.com/api/0_5_1/GetAcceptedCardType")
    @WebResult(name = "GetAcceptedCardTypeResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetAcceptedCardType", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetAcceptedCardType")
    @ResponseWrapper(localName = "GetAcceptedCardTypeResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetAcceptedCardTypeResponse")
    public GetAcceptedCardTypeResult getAcceptedCardType(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetAcceptedCardTypeRequest request);

    /**
     * Validates and completes a sale by processing all items added to a shopping cart.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.CheckoutShoppingCartResult
     */
    @WebMethod(operationName = "CheckoutShoppingCart", action = "http://clients.mindbodyonline.com/api/0_5_1/CheckoutShoppingCart")
    @WebResult(name = "CheckoutShoppingCartResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "CheckoutShoppingCart", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.CheckoutShoppingCart")
    @ResponseWrapper(localName = "CheckoutShoppingCartResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.CheckoutShoppingCartResponse")
    public CheckoutShoppingCartResult checkoutShoppingCart(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        CheckoutShoppingCartRequest request);

    /**
     * Gets a list of sales.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetSalesResult
     */
    @WebMethod(operationName = "GetSales", action = "http://clients.mindbodyonline.com/api/0_5_1/GetSales")
    @WebResult(name = "GetSalesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetSales", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSales")
    @ResponseWrapper(localName = "GetSalesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSalesResponse")
    public GetSalesResult getSales(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetSalesRequest request);

    /**
     * Gets a list of services available for sale.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetServicesResult
     */
    @WebMethod(operationName = "GetServices", action = "http://clients.mindbodyonline.com/api/0_5_1/GetServices")
    @WebResult(name = "GetServicesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetServices")
    @ResponseWrapper(localName = "GetServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetServicesResponse")
    public GetServicesResult getServices(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetServicesRequest request);

    /**
     * Update select services information.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.UpdateServicesResult
     */
    @WebMethod(operationName = "UpdateServices", action = "http://clients.mindbodyonline.com/api/0_5_1/UpdateServices")
    @WebResult(name = "UpdateServicesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "UpdateServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateServices")
    @ResponseWrapper(localName = "UpdateServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateServicesResponse")
    public UpdateServicesResult updateServices(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        UpdateServicesRequest request);

    /**
     * Gets a list of packages available for sale.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetPackagesResult
     */
    @WebMethod(operationName = "GetPackages", action = "http://clients.mindbodyonline.com/api/0_5_1/GetPackages")
    @WebResult(name = "GetPackagesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetPackages", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetPackages")
    @ResponseWrapper(localName = "GetPackagesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetPackagesResponse")
    public GetPackagesResult getPackages(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetPackagesRequest request);

    /**
     * Get a list of products available for sale.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetProductsResult
     */
    @WebMethod(operationName = "GetProducts", action = "http://clients.mindbodyonline.com/api/0_5_1/GetProducts")
    @WebResult(name = "GetProductsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetProducts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetProducts")
    @ResponseWrapper(localName = "GetProductsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetProductsResponse")
    public GetProductsResult getProducts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetProductsRequest request);

    /**
     * Update select products information.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.UpdateProductsResult
     */
    @WebMethod(operationName = "UpdateProducts", action = "http://clients.mindbodyonline.com/api/0_5_1/UpdateProducts")
    @WebResult(name = "UpdateProductsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "UpdateProducts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateProducts")
    @ResponseWrapper(localName = "UpdateProductsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateProductsResponse")
    public UpdateProductsResult updateProducts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        UpdateProductsRequest request);

    /**
     * Redeem a Spa Finder Gift Card.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.RedeemSpaFinderWellnessCardResult
     */
    @WebMethod(operationName = "RedeemSpaFinderWellnessCard", action = "http://clients.mindbodyonline.com/api/0_5_1/RedeemSpaFinderWellnessCard")
    @WebResult(name = "RedeemSpaFinderWellnessCardResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "RedeemSpaFinderWellnessCard", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.RedeemSpaFinderWellnessCard")
    @ResponseWrapper(localName = "RedeemSpaFinderWellnessCardResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.RedeemSpaFinderWellnessCardResponse")
    public RedeemSpaFinderWellnessCardResult redeemSpaFinderWellnessCard(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        RedeemSpaFinderWellnessCardRequest request);

    /**
     * Gets a list of Custom Payment Methods.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetCustomPaymentMethodsResult
     */
    @WebMethod(operationName = "GetCustomPaymentMethods", action = "http://clients.mindbodyonline.com/api/0_5_1/GetCustomPaymentMethods")
    @WebResult(name = "GetCustomPaymentMethodsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetCustomPaymentMethods", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetCustomPaymentMethods")
    @ResponseWrapper(localName = "GetCustomPaymentMethodsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetCustomPaymentMethodsResponse")
    public GetCustomPaymentMethodsResult getCustomPaymentMethods(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetCustomPaymentMethodsRequest request);

    /**
     * Return a sale used in business mode. This only supports comp payment method.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.ReturnSaleResult
     */
    @WebMethod(operationName = "ReturnSale", action = "http://clients.mindbodyonline.com/api/0_5_1/ReturnSale")
    @WebResult(name = "ReturnSaleResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "ReturnSale", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.ReturnSale")
    @ResponseWrapper(localName = "ReturnSaleResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.ReturnSaleResponse")
    public ReturnSaleResult returnSale(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        ReturnSaleRequest request);

    /**
     * Modify sale date in business mode
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.UpdateSaleDateResult
     */
    @WebMethod(operationName = "UpdateSaleDate", action = "http://clients.mindbodyonline.com/api/0_5_1/UpdateSaleDate")
    @WebResult(name = "UpdateSaleDateResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "UpdateSaleDate", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateSaleDate")
    @ResponseWrapper(localName = "UpdateSaleDateResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateSaleDateResponse")
    public UpdateSaleDateResult updateSaleDate(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        UpdateSaleDateRequest request);

    /**
     * Gets a list of contracts for a given location.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetContractsResult
     */
    @WebMethod(operationName = "GetContracts", action = "http://clients.mindbodyonline.com/api/0_5_1/GetContracts")
    @WebResult(name = "GetContractsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetContracts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetContracts")
    @ResponseWrapper(localName = "GetContractsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetContractsResponse")
    public GetContractsResult getContracts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetContractsRequest request);

    /**
     * Purchase a contract.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.PurchaseContractsResult
     */
    @WebMethod(operationName = "PurchaseContracts", action = "http://clients.mindbodyonline.com/api/0_5_1/PurchaseContracts")
    @WebResult(name = "PurchaseContractsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "PurchaseContracts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.PurchaseContracts")
    @ResponseWrapper(localName = "PurchaseContractsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.PurchaseContractsResponse")
    public PurchaseContractsResult purchaseContracts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        PurchaseContractsRequest request);

}
