
package com.mindbodyonline.clients.api._0_5_1.class_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Class_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClassX0020ServiceSoap {


    /**
     * Gets a list of classes.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetClassesResult
     */
    @WebMethod(operationName = "GetClasses", action = "http://clients.mindbodyonline.com/api/0_5_1/GetClasses")
    @WebResult(name = "GetClassesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetClasses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClasses")
    @ResponseWrapper(localName = "GetClassesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassesResponse")
    public GetClassesResult getClasses(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetClassesRequest request);

    /**
     * Update a list of visits.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.UpdateClientVisitsResult
     */
    @WebMethod(operationName = "UpdateClientVisits", action = "http://clients.mindbodyonline.com/api/0_5_1/UpdateClientVisits")
    @WebResult(name = "UpdateClientVisitsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "UpdateClientVisits", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateClientVisits")
    @ResponseWrapper(localName = "UpdateClientVisitsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.UpdateClientVisitsResponse")
    public UpdateClientVisitsResult updateClientVisits(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        UpdateClientVisitsRequest request);

    /**
     * Gets a class with a list of clients.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetClassVisitsResult
     */
    @WebMethod(operationName = "GetClassVisits", action = "http://clients.mindbodyonline.com/api/0_5_1/GetClassVisits")
    @WebResult(name = "GetClassVisitsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetClassVisits", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassVisits")
    @ResponseWrapper(localName = "GetClassVisitsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassVisitsResponse")
    public GetClassVisitsResult getClassVisits(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetClassVisitsRequest request);

    /**
     * Gets a list of class descriptions.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetClassDescriptionsResult
     */
    @WebMethod(operationName = "GetClassDescriptions", action = "http://clients.mindbodyonline.com/api/0_5_1/GetClassDescriptions")
    @WebResult(name = "GetClassDescriptionsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetClassDescriptions", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassDescriptions")
    @ResponseWrapper(localName = "GetClassDescriptionsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassDescriptionsResponse")
    public GetClassDescriptionsResult getClassDescriptions(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetClassDescriptionsRequest request);

    /**
     * Gets a list of enrollments.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetEnrollmentsResult
     */
    @WebMethod(operationName = "GetEnrollments", action = "http://clients.mindbodyonline.com/api/0_5_1/GetEnrollments")
    @WebResult(name = "GetEnrollmentsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetEnrollments", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetEnrollments")
    @ResponseWrapper(localName = "GetEnrollmentsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetEnrollmentsResponse")
    public GetEnrollmentsResult getEnrollments(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetEnrollmentsRequest request);

    /**
     * Gets a list of class schedules.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetClassSchedulesResult
     */
    @WebMethod(operationName = "GetClassSchedules", action = "http://clients.mindbodyonline.com/api/0_5_1/GetClassSchedules")
    @WebResult(name = "GetClassSchedulesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetClassSchedules", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassSchedules")
    @ResponseWrapper(localName = "GetClassSchedulesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetClassSchedulesResponse")
    public GetClassSchedulesResult getClassSchedules(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetClassSchedulesRequest request);

    /**
     * Adds clients to classes (signup).
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.AddClientsToClassesResult
     */
    @WebMethod(operationName = "AddClientsToClasses", action = "http://clients.mindbodyonline.com/api/0_5_1/AddClientsToClasses")
    @WebResult(name = "AddClientsToClassesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "AddClientsToClasses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.AddClientsToClasses")
    @ResponseWrapper(localName = "AddClientsToClassesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.AddClientsToClassesResponse")
    public AddClientsToClassesResult addClientsToClasses(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        AddClientsToClassesRequest request);

    /**
     * Adds a client to a class.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.AddClientsToClassesResult
     */
    @WebMethod(operationName = "AddClientToClass", action = "http://clients.mindbodyonline.com/api/0_5_1/AddClientToClass")
    @WebResult(name = "AddClientToClassResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "AddClientToClass", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.AddClientToClass")
    @ResponseWrapper(localName = "AddClientToClassResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.AddClientToClassResponse")
    public AddClientsToClassesResult addClientToClass(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        AddClientToClassRequest request);

    /**
     * Removes clients from classes.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.RemoveClientsFromClassesResult
     */
    @WebMethod(operationName = "RemoveClientsFromClasses", action = "http://clients.mindbodyonline.com/api/0_5_1/RemoveClientsFromClasses")
    @WebResult(name = "RemoveClientsFromClassesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "RemoveClientsFromClasses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.RemoveClientsFromClasses")
    @ResponseWrapper(localName = "RemoveClientsFromClassesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.RemoveClientsFromClassesResponse")
    public RemoveClientsFromClassesResult removeClientsFromClasses(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        RemoveClientsFromClassesRequest request);

    /**
     * Adds clients to enrollments (signup).
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.AddClientsToEnrollmentsResult
     */
    @WebMethod(operationName = "AddClientsToEnrollments", action = "http://clients.mindbodyonline.com/api/0_5_1/AddClientsToEnrollments")
    @WebResult(name = "AddClientsToEnrollmentsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "AddClientsToEnrollments", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.AddClientsToEnrollments")
    @ResponseWrapper(localName = "AddClientsToEnrollmentsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.AddClientsToEnrollmentsResponse")
    public AddClientsToEnrollmentsResult addClientsToEnrollments(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        AddClientsToEnrollmentsRequest request);

    /**
     * Removes client from enrollment waitlist
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.RemoveFromWaitlistResult
     */
    @WebMethod(operationName = "RemoveFromWaitlist", action = "http://clients.mindbodyonline.com/api/0_5_1/RemoveFromWaitlist")
    @WebResult(name = "RemoveFromWaitlistResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "RemoveFromWaitlist", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.RemoveFromWaitlist")
    @ResponseWrapper(localName = "RemoveFromWaitlistResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.RemoveFromWaitlistResponse")
    public RemoveFromWaitlistResult removeFromWaitlist(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        RemoveFromWaitlistRequest request);

    /**
     * Gets a list of semesters.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetSemestersResult
     */
    @WebMethod(operationName = "GetSemesters", action = "http://clients.mindbodyonline.com/api/0_5_1/GetSemesters")
    @WebResult(name = "GetSemestersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetSemesters", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSemesters")
    @ResponseWrapper(localName = "GetSemestersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSemestersResponse")
    public GetSemestersResult getSemesters(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetSemestersRequest request);

    /**
     * Gets a list of courses.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetCoursesResult
     */
    @WebMethod(operationName = "GetCourses", action = "http://clients.mindbodyonline.com/api/0_5_1/GetCourses")
    @WebResult(name = "GetCoursesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetCourses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetCourses")
    @ResponseWrapper(localName = "GetCoursesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetCoursesResponse")
    public GetCoursesResult getCourses(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetCoursesRequest request);

    /**
     * Get waitlist entries.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetWaitlistEntriesResult
     */
    @WebMethod(operationName = "GetWaitlistEntries", action = "http://clients.mindbodyonline.com/api/0_5_1/GetWaitlistEntries")
    @WebResult(name = "GetWaitlistEntriesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetWaitlistEntries", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetWaitlistEntries")
    @ResponseWrapper(localName = "GetWaitlistEntriesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetWaitlistEntriesResponse")
    public GetWaitlistEntriesResult getWaitlistEntries(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetWaitlistEntriesRequest request);

    /**
     * Substitutes the teacher for a class.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.SubstituteClassTeacherResult
     */
    @WebMethod(operationName = "SubstituteClassTeacher", action = "http://clients.mindbodyonline.com/api/0_5_1/SubstituteClassTeacher")
    @WebResult(name = "SubstituteClassTeacherResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "SubstituteClassTeacher", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.SubstituteClassTeacher")
    @ResponseWrapper(localName = "SubstituteClassTeacherResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.SubstituteClassTeacherResponse")
    public SubstituteClassTeacherResult substituteClassTeacher(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        SubstituteClassTeacherRequest request);

    /**
     * Substitutes the teacher for a class.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.SubstituteClassTeacherResult
     */
    @WebMethod(operationName = "SubtituteClassTeacher", action = "http://clients.mindbodyonline.com/api/0_5_1/SubtituteClassTeacher")
    @WebResult(name = "SubtituteClassTeacherResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "SubtituteClassTeacher", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.SubtituteClassTeacher")
    @ResponseWrapper(localName = "SubtituteClassTeacherResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.SubtituteClassTeacherResponse")
    public SubstituteClassTeacherResult subtituteClassTeacher(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        SubstituteClassTeacherRequest request);

    /**
     * Cancels a single class instance.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.CancelSingleClassResult
     */
    @WebMethod(operationName = "CancelSingleClass", action = "http://clients.mindbodyonline.com/api/0_5_1/CancelSingleClass")
    @WebResult(name = "CancelSingleClassResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "CancelSingleClass", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.CancelSingleClass")
    @ResponseWrapper(localName = "CancelSingleClassResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.CancelSingleClassResponse")
    public CancelSingleClassResult cancelSingleClass(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        CancelSingleClassRequest request);

}
