
package com.mindbodyonline.clients.api._0_5_1.class_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Provides methods and attributes relating to classes and enrollments.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Class_x0020_Service", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", wsdlLocation = "https://api.mindbodyonline.com/0_5_1/ClassService.asmx?WSDL")
public class ClassX0020Service
    extends Service
{

    private final static URL CLASSX0020SERVICE_WSDL_LOCATION;
    private final static WebServiceException CLASSX0020SERVICE_EXCEPTION;
    private final static QName CLASSX0020SERVICE_QNAME = new QName("http://clients.mindbodyonline.com/api/0_5_1", "Class_x0020_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.mindbodyonline.com/0_5_1/ClassService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSX0020SERVICE_WSDL_LOCATION = url;
        CLASSX0020SERVICE_EXCEPTION = e;
    }

    public ClassX0020Service() {
        super(__getWsdlLocation(), CLASSX0020SERVICE_QNAME);
    }

    public ClassX0020Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSX0020SERVICE_QNAME, features);
    }

    public ClassX0020Service(URL wsdlLocation) {
        super(wsdlLocation, CLASSX0020SERVICE_QNAME);
    }

    public ClassX0020Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSX0020SERVICE_QNAME, features);
    }

    public ClassX0020Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassX0020Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClassX0020ServiceSoap
     */
    @WebEndpoint(name = "Class_x0020_ServiceSoap")
    public ClassX0020ServiceSoap getClassX0020ServiceSoap() {
        return super.getPort(new QName("http://clients.mindbodyonline.com/api/0_5_1", "Class_x0020_ServiceSoap"), ClassX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassX0020ServiceSoap
     */
    @WebEndpoint(name = "Class_x0020_ServiceSoap")
    public ClassX0020ServiceSoap getClassX0020ServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://clients.mindbodyonline.com/api/0_5_1", "Class_x0020_ServiceSoap"), ClassX0020ServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSX0020SERVICE_EXCEPTION!= null) {
            throw CLASSX0020SERVICE_EXCEPTION;
        }
        return CLASSX0020SERVICE_WSDL_LOCATION;
    }

}
