
package com.mindbodyonline.clients.api._0_5_1.site_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Site_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
@XmlSeeAlso({
    com.mindbodyonline.clients.api._0_4.ObjectFactory.class,
    ObjectFactory.class
})
public interface SiteX0020ServiceSoap {


    /**
     * Gets a list of sites.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetSitesResult
     */
    @WebMethod(operationName = "GetSites", action = "http://clients.mindbodyonline.com/api/0_5_1/GetSites")
    @WebResult(name = "GetSitesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetSites", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSites")
    @ResponseWrapper(localName = "GetSitesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSitesResponse")
    public GetSitesResult getSites(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetSitesRequest request);

    /**
     * Gets a list of locations.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetLocationsResult
     */
    @WebMethod(operationName = "GetLocations", action = "http://clients.mindbodyonline.com/api/0_5_1/GetLocations")
    @WebResult(name = "GetLocationsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetLocations", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetLocations")
    @ResponseWrapper(localName = "GetLocationsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetLocationsResponse")
    public GetLocationsResult getLocations(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetLocationsRequest request);

    /**
     * Gets an activation code.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetActivationCodeResult
     */
    @WebMethod(operationName = "GetActivationCode", action = "http://clients.mindbodyonline.com/api/0_5_1/GetActivationCode")
    @WebResult(name = "GetActivationCodeResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetActivationCode", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetActivationCode")
    @ResponseWrapper(localName = "GetActivationCodeResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetActivationCodeResponse")
    public GetActivationCodeResult getActivationCode(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetActivationCodeRequest request);

    /**
     * Gets a list of programs.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetProgramsResult
     */
    @WebMethod(operationName = "GetPrograms", action = "http://clients.mindbodyonline.com/api/0_5_1/GetPrograms")
    @WebResult(name = "GetProgramsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetPrograms", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetPrograms")
    @ResponseWrapper(localName = "GetProgramsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetProgramsResponse")
    public GetProgramsResult getPrograms(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetProgramsRequest request);

    /**
     * Gets a list of session types.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetSessionTypesResult
     */
    @WebMethod(operationName = "GetSessionTypes", action = "http://clients.mindbodyonline.com/api/0_5_1/GetSessionTypes")
    @WebResult(name = "GetSessionTypesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetSessionTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSessionTypes")
    @ResponseWrapper(localName = "GetSessionTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetSessionTypesResponse")
    public GetSessionTypesResult getSessionTypes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetSessionTypesRequest request);

    /**
     * Gets a list of resources.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetResourcesResult
     */
    @WebMethod(operationName = "GetResources", action = "http://clients.mindbodyonline.com/api/0_5_1/GetResources")
    @WebResult(name = "GetResourcesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetResources", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetResources")
    @ResponseWrapper(localName = "GetResourcesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetResourcesResponse")
    public GetResourcesResult getResources(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetResourcesRequest request);

    /**
     * Gets a list of relationships.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetRelationshipsResult
     */
    @WebMethod(operationName = "GetRelationships", action = "http://clients.mindbodyonline.com/api/0_5_1/GetRelationships")
    @WebResult(name = "GetRelationshipsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetRelationships", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetRelationships")
    @ResponseWrapper(localName = "GetRelationshipsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetRelationshipsResponse")
    public GetRelationshipsResult getRelationships(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetRelationshipsRequest request);

    /**
     * Gets all resources schedule.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetResourceScheduleResult
     */
    @WebMethod(operationName = "GetResourceSchedule", action = "http://clients.mindbodyonline.com/api/0_5_1/GetResourceSchedule")
    @WebResult(name = "GetResourceScheduleResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetResourceSchedule", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetResourceSchedule")
    @ResponseWrapper(localName = "GetResourceScheduleResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetResourceScheduleResponse")
    public GetResourceScheduleResult getResourceSchedule(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetResourceScheduleRequest request);

    /**
     * Reserves a resource.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.ReserveResourceResult
     */
    @WebMethod(operationName = "ReserveResource", action = "http://clients.mindbodyonline.com/api/0_5_1/ReserveResource")
    @WebResult(name = "ReserveResourceResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "ReserveResource", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.ReserveResource")
    @ResponseWrapper(localName = "ReserveResourceResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.ReserveResourceResponse")
    public ReserveResourceResult reserveResource(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        ReserveResourceRequest request);

    /**
     * Gets a list of active mobile providers.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetMobileProvidersResult
     */
    @WebMethod(operationName = "GetMobileProviders", action = "http://clients.mindbodyonline.com/api/0_5_1/GetMobileProviders")
    @WebResult(name = "GetMobileProvidersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetMobileProviders", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetMobileProviders")
    @ResponseWrapper(localName = "GetMobileProvidersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetMobileProvidersResponse")
    public GetMobileProvidersResult getMobileProviders(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetMobileProvidersRequest request);

    /**
     * Gets a list of prospect stages for a site.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetProspectStagesResult
     */
    @WebMethod(operationName = "GetProspectStages", action = "http://clients.mindbodyonline.com/api/0_5_1/GetProspectStages")
    @WebResult(name = "GetProspectStagesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetProspectStages", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetProspectStages")
    @ResponseWrapper(localName = "GetProspectStagesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetProspectStagesResponse")
    public GetProspectStagesResult getProspectStages(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetProspectStagesRequest request);

    /**
     * Gets a list of prospect stages for a site.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5_1.GetGendersResult
     */
    @WebMethod(operationName = "GetGenders", action = "http://clients.mindbodyonline.com/api/0_5_1/GetGenders")
    @WebResult(name = "GetGendersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
    @RequestWrapper(localName = "GetGenders", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetGenders")
    @ResponseWrapper(localName = "GetGendersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", className = "com.mindbodyonline.clients.api._0_5_1.GetGendersResponse")
    public GetGendersResult getGenders(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1")
        GetGendersRequest request);

}
