
package com.mindbodyonline.clients.api._0_5_1.site_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Provides methods and attributes relating to sites and locations.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Site_x0020_Service", targetNamespace = "http://clients.mindbodyonline.com/api/0_5_1", wsdlLocation = "https://api.mindbodyonline.com/0_5_1/SiteService.asmx?WSDL")
public class SiteX0020Service
    extends Service
{

    private final static URL SITEX0020SERVICE_WSDL_LOCATION;
    private final static WebServiceException SITEX0020SERVICE_EXCEPTION;
    private final static QName SITEX0020SERVICE_QNAME = new QName("http://clients.mindbodyonline.com/api/0_5_1", "Site_x0020_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.mindbodyonline.com/0_5_1/SiteService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SITEX0020SERVICE_WSDL_LOCATION = url;
        SITEX0020SERVICE_EXCEPTION = e;
    }

    public SiteX0020Service() {
        super(__getWsdlLocation(), SITEX0020SERVICE_QNAME);
    }

    public SiteX0020Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SITEX0020SERVICE_QNAME, features);
    }

    public SiteX0020Service(URL wsdlLocation) {
        super(wsdlLocation, SITEX0020SERVICE_QNAME);
    }

    public SiteX0020Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SITEX0020SERVICE_QNAME, features);
    }

    public SiteX0020Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiteX0020Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiteX0020ServiceSoap
     */
    @WebEndpoint(name = "Site_x0020_ServiceSoap")
    public SiteX0020ServiceSoap getSiteX0020ServiceSoap() {
        return super.getPort(new QName("http://clients.mindbodyonline.com/api/0_5_1", "Site_x0020_ServiceSoap"), SiteX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiteX0020ServiceSoap
     */
    @WebEndpoint(name = "Site_x0020_ServiceSoap")
    public SiteX0020ServiceSoap getSiteX0020ServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://clients.mindbodyonline.com/api/0_5_1", "Site_x0020_ServiceSoap"), SiteX0020ServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SITEX0020SERVICE_EXCEPTION!= null) {
            throw SITEX0020SERVICE_EXCEPTION;
        }
        return SITEX0020SERVICE_WSDL_LOCATION;
    }

}
